### ISSUE TITLE
Nextcloud 23 - "The appinfo/database.xml file is not longer supported"

### ISSUE THREAD

**Issue by Breitling1992** [alexstocker/sensorlogger#106] opened 2022-05-06 14:39 UTC
It would be great, if you could update the app to work again with Nextcloud 23. 
I tried to install it manually, but i failed with the migration. 

https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html#

**Comment by stefan123t** [comment] 2022-09-06 01:04
looks like a duplicate of #103 isn't it ?

**Comment by p-bo** [comment] 2022-12-01 13:31
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Closed** 2024-01-04 11:39 UTC
