### ISSUE TITLE
Error after widget was added

### ISSUE THREAD

**Issue by mikoladz** [alexstocker/sensorlogger#68] opened 2019-01-23 21:34 UTC
Hello,

I have just started playing with sensorlogger and encountered an issue. I have added a device and some test data with the provided php scripts. Next I have added a widget on the dashboard. I am now trying to open the app and it fails.
## Expected Behavior
Opening https://mycloud/apps/sensorlogger/ should show me the dashboard.

## Actual Behavior
An error page is displayed. The log says:

Error | index | Error: Call to a member function getDescription() on boolean/var/www/html/nextcloud/apps/sensorlogger/lib/Widgets.php - line 101: OCA\SensorLogger\Widgets::build("12345678-ab ... 9", OCA\SensorLo ... 2}, stdClass { w ... "}, OC\DB\Connection {}, OC\AllConfig {})/var/www/html/nextcloud/apps/sensorlogger/controller/sensorloggercontroller.php - line 368: OCA\SensorLogger\Widgets->buildUserWidget("12345678-ab ... 9", OCA\SensorLo ... 2}, stdClass { w ... "}, OC\DB\Connection {}, OC\AllConfig {})/var/www/html/nextcloud/apps/sensorlogger/controller/sensorloggercontroller.php - line 145: OCA\SensorLogger\Controller\SensorLoggerController->getWidgets()/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\SensorLogger\Controller\SensorLoggerController->index()/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\SensorLo ... {}, "index")/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\SensorLo ... {}, "index")/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Sensor ... r", "index", OC\AppFramew ... {}, { _route: "s ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})/var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/html/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/sensorlogger/")/var/www/html/nextcloud/index.php - line 42: OC::handleRequest() | 2019-01-23T22:16:09+0100
-- | -- | -- | --
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$type at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#69 | 2019-01-23T22:16:09+0100
Error | PHP | Undefined property: stdClass::$short at /var/www/html/nextcloud/apps/sensorlogger/lib/LogExtended.php#68 | 2019-01-23T22:16:09+0100

## Steps to Reproduce the Problem

  1. Send data to sensorlogger with post.php script.
  2. Add a widget to the dashboard.
  3. Go to https://mycloud/apps/sensorlogger/

## Specifications

  - Version: NC 14.0.6, sensorlogger 0.0.9
  - Platform: Debian stable, PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
  - Subsystem:

**Comment by alexstocker** [comment] 2019-01-24 10:19
Thanx for your report and sorry that should not happen. 

Investigate asap

kindest
Alex

**Comment by alexstocker** [comment] 2019-01-24 10:23
Did you install SensorLogger from marketplace or from Git Repo?

**Comment by mikoladz** [comment] 2019-01-24 10:46
The app has been installed from the marketplace.

**Comment by alexstocker** [comment] 2019-01-24 23:19
Sorry. Can not reproduce reported problem. Have you tried to reinstall SensorLogger?

**Comment by alexstocker** [comment] 2019-01-24 23:20
What widget did you add?

**Comment by alexstocker** [comment] 2019-01-27 19:37
@mikoladz 
Tested with 
NC 14.0.6, PHP 7.0, PHP 7.2, Apache 2.4, mod_php and php-fpm, Ubuntu 18.04
NC 15.0.2, PHP 7.0, PHP 7.2, Apache 2.4, mod_php and php-fpm, Ubuntu 18.04
still not reproduceable by me.

Those undefined Property Error should not bother you. Fixed by @OzzieIsaacs on devel-nc branch.

Btw. @OzzieIsaacs can you have a look at this problem and trying to reproduce it? Thanx for your effort in advance.

**Comment by OzzieIsaacs** [comment] 2019-01-28 20:02
Tested with sensorlogger 0.0.9 (freshly updated today)
NC 15.0.0, PHP 7.2, Apache 2.4, Linux Mint 19.1 (based on Ubuntu 18.04), Mysql-server 5.7. I tried to mix default entries (only temperature, humidity as provided from post.php) and customized datatype entries on one sensor. Deleted several entries from other sensors. Always possible to create widget. Started fresh sensorlogger databases. Tested several widget types, tried to save only half configured widgets (only type selected)-> Could not create widget, but no log entry. 
I think for reproducing the issue it's mandatory to get copys of the oc_sensorlogger_* tables from the affected instance.
(According to my experience the undefined property error has to effect on the storage of the data in the database)

**Comment by alexstocker** [comment] 2019-01-30 00:21
@OzzieIsaacs 
Thanx for your effort. Currently trying to set these undefined properties within ExtendetLog::__constructor does not make any sense. I'm going to remove them.

@mikoladz 
Can you provide some more information or did you solve this problem by your own? Without further information it's just not possible to figure out the core of the problem and this issue. Going to close this issue soon.

**Comment by alexstocker** [comment] 2019-02-02 19:51
Sorry. That doesn't sounds good! I think there is something wrong with widget settings you configured earlier. But to fix this you need to have access to your database (cli or DBMS). Do you? (Hint: a DBMS for instance would be phpMyadmin)

If yes, 

`SELECT * FROM oc_preferences WHERE appid = 'sensorlogger';`

you should end up with something like this

![auswahl_001](https://user-images.githubusercontent.com/6260467/52168452-db211980-272a-11e9-99da-23ad81abacd2.png)

Depends on how many widgets you configured. Now, delete them. If the problem was in there it now should be gone. If not - bad thing.

Additional Information:
These are all sensorlogger tables created on install.
oc_sensorlogger_data_types
oc_sensorlogger_devices
oc_sensorlogger_device_data_types
oc_sensorlogger_device_groups
oc_sensorlogger_device_types
oc_sensorlogger_logs

**Comment by alexstocker** [comment] 2019-02-10 18:49
@mikoladz 
Please reopen this issue as soon as you can provide further information.

**Closed by alexstocker** 2019-02-10 18:49 UTC
Labels: bug, nc
